### ISSUE TITLE
Navigation Refresh when Cut-Paste

### ISSUE THREAD

**Issue by warriors03** [indiana-university/kumo#1]
We've found that when a user cuts and pastes files, the source folder doesn't reflect the changes.
You can reproduce by:
1. Cutting two or more files (occasionally happens with 1, but consistently with 2)
2. Navigating to another folder
3. Paste the files
4. Navigating back to the original folder.  You should see the files still showing, but if you try and access/delete them, it throws an error that they don’t exist

.We tried a f5/refresh and navigating away and back, and can’t seem to get those files to disappear without a close and re-open of the client

Kumo Version 3.1.3.101

**Comment by jhoerr** [comment]
@warriors03 Can you confirm that this is reproducible on the latest version of (3.2.1) client?

**Comment by warriors03** [comment]
@jhoerr  - Yes, this issue presents on Client Version 3.2.1 for us.  Are you able to reproduce on your end?

**Comment by jhoerr** [comment]
@warriors03 have had a chance to repro it yet. More questions for you:  
1. If you browse to the originating folder on the storage provider's site, do the files appear to have been 'cut' as expected?
2. Does this also occur across services, for example when cutting/pasting from Dropbox to Box?

**Comment by warriors03** [comment]
@jhoerr  - 
1. Yes, the files show as expected on the providers site
2. No, after pasting into dropbox and navigating back to box, the files were gone as expected.  Seemed like folder refreshed the view when navigating back to box.

**Comment by jhoerr** [comment]
I'm able to reproduce this. It occurs only for files that were opened (downloaded) prior to being moved. This was root-caused to bug in our caching layer.

**Comment by jhoerr** [comment]
@warriors03 I've posted a client beta, 3.2.2-beta4, which contains a fix for this bug. Can you install it and confirm that you can no longer reproduce the issue?

**Comment by warriors03** [comment]
Yep, but it will likely be a week or two before I can get to it right now.  Sorry, slammed with semester break fun

**Comment by jhoerr** [comment]
Ok, no problem. I'm going forward with the release (it fixes a few other pressing issues) but still want to get your confirmation as you're able.

**Comment by jhoerr** [comment]
Now that the 3.2.2 client has been released I'm going to close this. Feel free to re-open if the bug is still present.
