### ISSUE TITLE
Client becomes unresponsive when retrieving deleted file

### ISSUE THREAD

**Issue by jardrake** [indiana-university/kumo#9]
If the client is downloading a large file that is deleted during the chunk downloads, the application will become unresponsive. Browsing through the kumo folders also stops working. 

I've tested with:
* PDF in Acrobat (97mb)
* MP4 in Windows Media Player (50mb)
* PDF in Acrobat (5mb) - I deleted the file from Box as soon as I clicked "Open in Acrobat". This caused the entire file system to become unresponsive.

**Comment by jhoerr** [comment]
This was fixed for 3.3.0beta-1
